name: Android CI

on:
  push:
    tags:
    - 'v*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
    - name: Set up Python 3.9.1
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.1'
        architecture: 'x64'
    - name: Grant execute permission for init.sh
      run: chmod +x init.sh
    - name: Grant execute permission for makeffi.sh
      run: chmod +x makeffi.sh
    - name: Grant execute permission for makepy.sh
      run: chmod +x makepy.sh
    - name: Grant execute permission for upload.sh
      run: chmod +x upload.sh
    - name: init
      run: ./init.sh
    - name: makeffi aarch64
      run: ./makeffi.sh aarch64-linux-android
    - name: makepy aarch64
      run: ./makepy.sh aarch64-linux-android
    - name: upload aarch64
      run: ./upload.sh aarch64-linux-android
    - name: makeffi arm
      run: ./makeffi.sh arm-linux-androideabi
    - name: makepy arm
      run: ./makepy.sh arm-linux-androideabi
    - name: upload arm
      run: ./upload.sh arm-linux-androideabi
    - name: makeffi i686
      run: ./makeffi.sh i686-linux-android
    - name: makepy i686
      run: ./makepy.sh i686-linux-android
    - name: upload i686
      run: ./upload.sh i686-linux-android
    - name: makeffi x86_64
      run: ./makeffi.sh x86_64-linux-android
    - name: makepy x86_64
      run: ./makepy.sh x86_64-linux-android
    - name: upload x86_64
      run: ./upload.sh x86_64-linux-android
    - name: Build zip file
      run: |
        zip libs.zip *.a
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./libs.zip
        asset_name: libs.zip
        asset_content_type: application/zip
